# Generated by Django 5.2.1 on 2025-05-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
