version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerceuser
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: ecommerce_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ecommerce
      DB_USER: ecommerceuser
      DB_PASSWORD: strongpassword
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: